package nhanh1;

import java.awt.Component;
import java.awt.Font;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien do hoa (GUI) truc quan cho Nhanh 1:
 * So sanh Byte Stream (FileInputStream/FileOutputStream) va Character Stream (FileReader/FileWriter).
 *
 * Chuc nang:
 * 1. Chon file dau vao (.txt) hoac dung file mau benchmark san co.
 * 2. Do thoi gian doc/xu ly thuc te bang SwingWorker chay tren background thread.
 * 3. Dong bo Console output vao JTextArea realtime.
 * 4. Bang ket qua JTable tong hop truc quan (ByteStream vs CharStream).
 */
public class MainForm extends javax.swing.JFrame {

    private SwingWorker<Void, String> benchmarkWorker;
    private long measuredByteTime = -1;
    private long measuredCharTime = -1;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap bo sung sau khi khoi tao giao dien initComponents().
     */
    private void customInit() {
        // Can giua man hinh
        setLocationRelativeTo(null);

        // Tim file mau mac dinh
        File defaultFile = new File("src/nhanh1/sample.txt");
        if (defaultFile.exists()) {
            txtFilePath.setText(defaultFile.getAbsolutePath());
        } else {
            File altFile = new File("src/nhanh1/benchmark_temp.txt");
            if (altFile.exists()) {
                txtFilePath.setText(altFile.getAbsolutePath());
            } else {
                txtFilePath.setText("src/nhanh1/sample.txt");
            }
        }

        // Dinh dang bang ket qua
        tblResult.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblResult.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblResult.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblResult.getColumnModel().getColumn(2).setPreferredWidth(260);

        // Can giua cot Thoi gian (ms)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblResult.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);

        // Thong bao khoi dong
        txtLog.append("=== CHUONG TRINH SO SANH BYTE STREAM VS CHARACTER STREAM ===\n");
        txtLog.append("- Nhấn 'Chọn File...' để chọn tệp văn bản hoặc dùng tệp mặc định.\n");
        txtLog.append("- Nhấn 'Chạy So Sánh' để bắt đầu đo lường hiệu năng.\n");
        txtLog.append("- Hệ thống sử dụng SwingWorker để đảm bảo giao diện luôn mượt mà.\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnChooseFile = new javax.swing.JButton();
        txtFilePath = new javax.swing.JTextField();
        btnRun = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        scpResult = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 1 - So sánh Byte Stream vs Character Stream");
        setMinimumSize(new java.awt.Dimension(720, 600));
        setPreferredSize(new java.awt.Dimension(780, 650));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SO SÁNH HIỆU NĂNG: BYTE STREAM VS CHARACTER STREAM");
        pnlControl.add(lblTitle);

        btnChooseFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChooseFile.setText("Chọn File...");
        btnChooseFile.setToolTipText("Chọn tệp tin văn bản (.txt) để thử nghiệm");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });
        pnlControl.add(btnChooseFile);

        txtFilePath.setEditable(false);
        txtFilePath.setToolTipText("Đường dẫn file đã chọn");
        pnlControl.add(txtFilePath);

        btnRun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRun.setText("Chạy So Sánh");
        btnRun.setToolTipText("Bắt đầu quá trình kiểm thử so sánh giữa 2 luồng");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        pnlControl.add(btnRun);

        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStop.setText("Dừng");
        btnStop.setToolTipText("Huỷ quá trình thử nghiệm đang chạy");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        pnlControl.add(btnStop);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Sŕn sàng");
        pnlControl.add(lblStatus);

        progressBar.setString("");
        progressBar.setStringPainted(true);
        pnlControl.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ THỰC THI (LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtLog.setRows(5);
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResult.setText("KẾT QUẢ SO SÁNH:");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ByteStream (FileInputStream)", null, "Đọc nhị phân (8-bit), không decode"},
                {"CharStream (FileReader UTF-8)", null, "Đọc ký tự Unicode, giải mã UTF-8"}
            },
            new String [] {
                "Phương pháp", "Thời gian (ms)", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResult.setRowHeight(24);
        scpResult.setViewportView(tblResult);

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpResult)
                    .addGroup(pnlResultLayout.createSequentialGroup()
                        .addComponent(lblResult)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpResult, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien nut Chon File.
     */
    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn tệp văn bản thử nghiệm");
        chooser.setFileFilter(new FileNameExtensionFilter("Text & Data files (*.txt, *.dat, *.log, *.csv)", "txt", "dat", "log", "csv"));

        File current = new File(txtFilePath.getText().trim());
        if (current.exists()) {
            chooser.setSelectedFile(current);
        } else {
            chooser.setCurrentDirectory(new File("src/nhanh1"));
        }

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selected = chooser.getSelectedFile();
            txtFilePath.setText(selected.getAbsolutePath());
            txtLog.append(String.format("-> [Hệ thống] Đã chọn tệp: %s (Kích thước: %,d bytes)\n",
                    selected.getName(), selected.length()));
            lblStatus.setText("Trạng thái: Đã chọn " + selected.getName());
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed

    /**
     * Xu ly su kien nut Chay So Sanh.
     */
    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        final String filePath = txtFilePath.getText().trim();
        if (filePath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đường dẫn tệp!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        File targetFile = new File(filePath);
        if (!targetFile.exists()) {
            // Neu file chua co va ten file chua benchmark, tu sinh file 1MB
            if (filePath.contains("benchmark")) {
                try {
                    PerformanceComparator.generateBenchmarkFile(filePath, 1024);
                    targetFile = new File(filePath);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Không thể tự động sinh file benchmark: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tệp tin không tồn tại: " + filePath, "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Cap nhat trang thai UI
        btnRun.setEnabled(false);
        btnChooseFile.setEnabled(false);
        btnStop.setEnabled(true);
        progressBar.setIndeterminate(true);
        progressBar.setString("Đang đo lường hiệu năng...");
        lblStatus.setText("Trạng thái: Đang thực thi đo lường...");

        // Reset bang ket qua
        DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
        model.setValueAt("-", 0, 1);
        model.setValueAt("-", 1, 1);

        txtLog.append("\n=======================================================\n");
        txtLog.append("BẮT ĐẦU ĐO HIỆU NĂNG BYTE STREAM VS CHARACTER STREAM\n");
        txtLog.append(String.format("Tệp thử nghiệm: %s (%,d bytes ~ %.2f MB)\n",
                targetFile.getAbsolutePath(), targetFile.length(), targetFile.length() / (1024.0 * 1024.0)));
        txtLog.append("=======================================================\n");

        final File testFile = targetFile;

        // SwingWorker thuc thi blocking IO tren background thread
        benchmarkWorker = new SwingWorker<Void, String>() {
            private long byteTime = -1;
            private long charTime = -1;
            private PrintStream oldOut;
            private PrintStream oldErr;

            @Override
            protected Void doInBackground() throws Exception {
                // Chuyen huong System.out va System.err vao SwingWorker log
                oldOut = System.out;
                oldErr = System.err;
                PrintStream customOut = new PrintStream(new OutputStream() {
                    private ByteArrayOutputStream baos = new ByteArrayOutputStream();

                    @Override
                    public void write(int b) {
                        if (b == '\n') {
                            String line = baos.toString(StandardCharsets.UTF_8);
                            publish(line);
                            baos.reset();
                        } else {
                            baos.write(b);
                        }
                    }
                }, true, StandardCharsets.UTF_8);

                System.setOut(customOut);
                System.setErr(customOut);

                try {
                    publish("[BƯỚC 1] Bắt đầu đo ByteStream (FileInputStream)...");
                    byteTime = ByteStreamDemo.readAndMeasure(testFile.getAbsolutePath());
                    publish(String.format("-> [ByteStream] Đọc xong: %,d ms", byteTime));

                    if (isCancelled()) {
                        return null;
                    }

                    publish("\n[BƯỚC 2] Bắt đầu đo Character Stream (FileReader UTF-8)...");
                    charTime = CharStreamDemo.readAndMeasure(testFile.getAbsolutePath());
                    publish(String.format("-> [CharStream] Đọc xong: %,d ms", charTime));

                    if (isCancelled()) {
                        return null;
                    }

                    // Minh hoa chenh lech giai ma ky tu
                    publish("\n[BƯỚC 3] Kiểm tra tính toàn vẹn ký tự Unicode tiếng Việt...");
                    PerformanceComparator.demonstrateEncodingDifference(testFile.getAbsolutePath());

                    publish("\n------------------ TỔNG KẾT ------------------");
                    publish(String.format("1. ByteStream : %,d ms (Xử lý mức byte nhị phân 8-bit)", byteTime));
                    publish(String.format("2. CharStream : %,d ms (Xử lý mức ký tự Unicode qua Charset UTF-8)", charTime));
                    if (byteTime < charTime) {
                        publish("=> ByteStream nhanh hơn do không tốn chi phí giải mã (Decode) UTF-8.");
                    } else if (byteTime > charTime) {
                        publish("=> CharStream tối ưu hóa tốt hơn cho tập ký tự trong môi trường này.");
                    } else {
                        publish("=> Cả hai phương pháp hoàn thành trong khoảng thời gian tương đương.");
                    }
                    publish("----------------------------------------------");

                } finally {
                    System.setOut(oldOut);
                    System.setErr(oldErr);
                }

                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                for (String chunk : chunks) {
                    txtLog.append(chunk + "\n");
                }
                // Tu dong cuon xuong cuoi
                txtLog.setCaretPosition(txtLog.getDocument().getLength());
            }

            @Override
            protected void done() {
                btnRun.setEnabled(true);
                btnChooseFile.setEnabled(true);
                btnStop.setEnabled(false);
                progressBar.setIndeterminate(false);

                if (isCancelled()) {
                    progressBar.setValue(0);
                    progressBar.setString("Đã dừng");
                    lblStatus.setText("Trạng thái: Quá trình đã bị huỷ bởi người dùng");
                    txtLog.append("\n[HỆ THỐNG] Quá trình đo đạc đã dừng!\n");
                } else {
                    progressBar.setValue(100);
                    progressBar.setString("Hoàn tất 100%");
                    lblStatus.setText("Trạng thái: Hoàn tất đo lường");

                    measuredByteTime = byteTime;
                    measuredCharTime = charTime;

                    // Cap nhat bang ket qua
                    DefaultTableModel resModel = (DefaultTableModel) tblResult.getModel();
                    resModel.setValueAt(byteTime + " ms", 0, 1);
                    resModel.setValueAt(charTime + " ms", 1, 1);

                    txtLog.append("\n[HỆ THỐNG] Đã cập nhật kết quả vào bảng JTable thành công!\n");
                }
            }
        };

        benchmarkWorker.execute();
    }//GEN-LAST:event_btnRunActionPerformed

    /**
     * Xu ly su kien nut Dung.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (benchmarkWorker != null && !benchmarkWorker.isDone()) {
            benchmarkWorker.cancel(true);
            txtLog.append("-> [Hệ thống] Đang yêu cầu dừng worker...\n");
        }
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JScrollPane scpResult;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
