package nhanh5;

import java.awt.Font;
import java.net.SocketTimeoutException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien UDP Client (DatagramSocket / DatagramPacket Ping-Pong).
 *
 * Chuc nang chinh:
 * 1. Cau hinh Server Host (localhost) va Port UDP (9191).
 * 2. Nhap thong diep gui (mac dinh: 'Ping') va chon so luong goi tin gui (1 - 100 goi).
 * 3. Thuc thi gui goi tin DatagramPacket tren SwingWorker, do do tre (latency) tung goi.
 * 4. Hien thi phan hoi: "Sent: Ping -> Received: Pong" theo dung dac ta bao cao.
 * 5. Thong ke ty le mat goi (Packet Loss) do dac tinh khong tin cay cua UDP.
 */
public class ClientForm extends javax.swing.JFrame {

    private int totalPacketsSent = 0;
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblHistory.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblHistory.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblHistory.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(2).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(3).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(4).setPreferredWidth(90);
        tblHistory.getColumnModel().getColumn(5).setPreferredWidth(120);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblHistory.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

        txtLog.append("=== UDP CLIENT (DATAGRAM SOCKET PING-PONG) SẴN SÀNG ===\n");
        txtLog.append("- Cấu hình Server Host, Port và chuỗi gửi (mặc định: 'Ping').\n");
        txtLog.append("- Chọn số lần gửi (từ 1 đến 100 gói UDP) để kiểm thử tính truyền nhận và mất gói.\n");
        txtLog.append("- Bấm 'Gửi UDP (Send)' hoặc nhấn Enter để truyền gói tin DatagramPacket.\n");
        txtLog.append("- Nhận và kiểm tra phản hồi theo định dạng: Sent: Ping -> Received: Pong.\n\n");
    }

    private void appendLog(String message) {
        txtLog.append(message + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfig = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        pnlMessage = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        lblCount = new javax.swing.JLabel();
        spinCount = new javax.swing.JSpinner();
        btnSend = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlHistory = new javax.swing.JPanel();
        lblHistory = new javax.swing.JLabel();
        scpHistory = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 5 - UDP Client (DatagramSocket Ping-Pong)");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("UDP CLIENT - GỬI GÓI TIN DATAGRAMPACKET (PING - PONG)");
        pnlConfig.add(lblTitle);

        lblHost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHost.setText("Server Host:");
        pnlConfig.add(lblHost);

        txtHost.setText("localhost");
        txtHost.setToolTipText("Địa chỉ IP hoặc hostname máy chủ UDP");
        pnlConfig.add(txtHost);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlConfig.add(lblPort);

        txtPort.setText("9191");
        txtPort.setToolTipText("Cổng UDPServer (mặc định 9191)");
        pnlConfig.add(txtPort);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMessage.setText("Thông điệp gửi:");
        pnlMessage.add(lblMessage);

        txtMessage.setText("Ping");
        txtMessage.setToolTipText("Nhập chuỗi (mặc định Ping để nhận Pong)");
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        pnlMessage.add(txtMessage);

        lblCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCount.setText("Số lần gửi:");
        pnlMessage.add(lblCount);

        spinCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spinCount.setToolTipText("Số lượng gói tin UDP cần gửi (1 - 100)");
        pnlMessage.add(spinCount);

        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setText("Gửi UDP (Send)");
        btnSend.setToolTipText("Gửi DatagramPacket qua UDP va chờ phản hồi");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        pnlMessage.add(btnSend);

        btnClearLog.setText("Xóa Lịch Sử");
        btnClearLog.setToolTipText("Xóa nhật ký log và bảng lịch sử");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        pnlMessage.add(btnClearLog);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Sẵn sàng");
        pnlMessage.add(lblStatus);

        progressBar.setString("Sẵn sàng gửi");
        progressBar.setStringPainted(true);
        pnlMessage.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ TRUYỀN NHẬN UDP (LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHistory.setText("LỊCH SỬ GÓI TIN UDP VÀ PHẢN HỒI TỬ SERVER:");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gói #", "Thời gian", "Thông điệp gửi", "Phản hồi nhận", "Độ trễ (ms)", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistory.setRowHeight(22);
        scpHistory.setViewportView(tblHistory);

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpHistory)
                    .addGroup(pnlHistoryLayout.createSequentialGroup()
                        .addComponent(lblHistory)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien khi nhan Enter tren txtMessage.
     */
    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        executeSendPackets();
    }//GEN-LAST:event_txtMessageActionPerformed

    /**
     * Xu ly su kien nut Send.
     */
    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        executeSendPackets();
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * Xu ly su kien nut Xoa Lich Su.
     */
    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtLog.setText("");
        DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
        model.setRowCount(0);
        totalPacketsSent = 0;
        appendLog("-> Đã xóa sạch nhật ký log và lịch sử gói tin UDP.\n");
    }//GEN-LAST:event_btnClearLogActionPerformed

    /**
     * Thuc thi gui N goi tin DatagramPacket tren SwingWorker.
     */
    private void executeSendPackets() {
        String host = txtHost.getText().trim();
        if (host.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ UDPServer Host!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int port;
        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port phải nằm trong khoảng (1 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String message = txtMessage.getText();
        if (message == null || message.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông điệp cần gửi!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int count = (Integer) spinCount.getValue();
        if (count < 1 || count > 100) {
            JOptionPane.showMessageDialog(this, "Số lần gửi phải từ 1 đến 100!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnSend.setEnabled(false);
        txtMessage.setEnabled(false);
        spinCount.setEnabled(false);
        progressBar.setMinimum(0);
        progressBar.setMaximum(count);
        progressBar.setValue(0);
        progressBar.setIndeterminate(false);
        progressBar.setString(String.format("Đang gửi 0/%d gói UDP...", count));
        lblStatus.setText(String.format("Trạng thái: Bắt đầu gửi %d gói tới %s:%d...", count, host, port));

        SwingWorker<Void, Object[]> worker = new SwingWorker<Void, Object[]>() {
            private int successCount = 0;
            private int lossCount = 0;
            private long totalLatency = 0;

            @Override
            protected Void doInBackground() throws Exception {
                UDPClient client = new UDPClient(host, port);

                for (int i = 1; i <= count; i++) {
                    if (isCancelled()) break;

                    String timeStr = LocalTime.now().format(timeFormatter);
                    long start = System.currentTimeMillis();

                    try {
                        String response = client.sendAndReceive(message);
                        long elapsed = System.currentTimeMillis() - start;
                        successCount++;
                        totalLatency += elapsed;

                        String status = "Pong".equalsIgnoreCase(response) ? "Thành công (OK)" : "Phản hồi khác";
                        publish(new Object[]{i, timeStr, message, response, elapsed, status, true});

                    } catch (SocketTimeoutException e) {
                        long elapsed = System.currentTimeMillis() - start;
                        lossCount++;
                        publish(new Object[]{i, timeStr, message, "[Mất gói / Timeout]", elapsed, "Mất gói (Loss)", false});

                    } catch (Exception e) {
                        lossCount++;
                        String err = e.getMessage() != null ? e.getMessage() : "Lỗi Socket";
                        publish(new Object[]{i, timeStr, message, "[Lỗi] " + err, 0L, "Thất bại", false});
                    }

                    // Cho nhe giua cac goi tin neu gui nhieu goi
                    if (count > 1 && i < count) {
                        Thread.sleep(80);
                    }
                }
                return null;
            }

            @Override
            protected void process(List<Object[]> chunks) {
                DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
                for (Object[] item : chunks) {
                    int packetNum = (Integer) item[0];
                    String timeStr = (String) item[1];
                    String sentMsg = (String) item[2];
                    String respMsg = (String) item[3];
                    long elapsed = (Long) item[4];
                    String status = (String) item[5];
                    boolean ok = (Boolean) item[6];

                    totalPacketsSent++;
                    model.addRow(new Object[]{totalPacketsSent, timeStr, sentMsg, respMsg, elapsed, status});

                    // In theo dung dac ta: Sent: Ping -> Received: Pong
                    if (ok) {
                        appendLog(String.format("Sent: %s -> Received: %s (%d ms)", sentMsg, respMsg, elapsed));
                    } else {
                        appendLog(String.format("Sent: %s -> %s", sentMsg, respMsg));
                    }

                    progressBar.setValue(packetNum);
                    progressBar.setString(String.format("Đã gửi %d/%d gói UDP", packetNum, count));
                }
            }

            @Override
            protected void done() {
                btnSend.setEnabled(true);
                txtMessage.setEnabled(true);
                spinCount.setEnabled(true);
                txtMessage.requestFocusInWindow();

                long avgLatency = (successCount > 0) ? (totalLatency / successCount) : 0;
                double lossRate = (count > 0) ? ((double) lossCount / count * 100.0) : 0;

                lblStatus.setText(String.format("Hoàn tất: %d/%d gói OK | Mất: %d (%.1f%%) | Độ trễ TB: %d ms",
                        successCount, count, lossCount, lossRate, avgLatency));
                progressBar.setString(String.format("Xong! %d/%d thành công", successCount, count));
                appendLog(String.format("-> [Tổng kết] Thành công: %d/%d | Mất gói: %d (%.1f%%) | Độ trễ TB: %d ms\n",
                        successCount, count, lossCount, lossRate, avgLatency));
            }
        };

        worker.execute();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Look and Feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()) || "Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpHistory;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JSpinner spinCount;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
