package nhanh5;

import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien UDP Server (DatagramSocket / DatagramPacket Ping-Pong).
 *
 * Chuc nang chinh:
 * 1. Cau hinh cong Port UDP lang nghe (mac dinh: 9191).
 * 2. Start / Stop Server an toan tren SwingWorker, khong lam do UI.
 * 3. Hien thi thong tin goi tin nhan va phan hoi (Ping -> Pong).
 * 4. Luu tru danh sach cac goi tin DatagramPacket vao JTable realtime.
 */
public class ServerForm extends javax.swing.JFrame {

    private UDPServer server;
    private SwingWorker<Void, Void> serverWorker;
    private int packetCounter = 0;
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblPackets.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblPackets.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblPackets.getColumnModel().getColumn(1).setPreferredWidth(90);
        tblPackets.getColumnModel().getColumn(2).setPreferredWidth(180);
        tblPackets.getColumnModel().getColumn(3).setPreferredWidth(170);
        tblPackets.getColumnModel().getColumn(4).setPreferredWidth(170);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblPackets.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblPackets.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);

        // Xu ly su kien khi dong Form thi tu dong dung Server an toan
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                stopServer();
            }
        });

        txtLog.append("=== MÁY CHỦ UDP PING-PONG (DATAGRAM SOCKET) SẴN SÀNG ===\n");
        txtLog.append("- Cấu hình cổng UDP lắng nghe (mặc định: 9191).\n");
        txtLog.append("- Nhấn 'Start Server' để bắt đầu hứng các gói tin DatagramPacket.\n");
        txtLog.append("- Khi nhận 'Ping', Server sẽ tự động đóng gói chuỗi 'Pong' gửi ngược lại Client.\n");
        txtLog.append("- Nhấn 'Stop Server' để đóng DatagramSocket an toàn.\n\n");
    }

    private void appendLog(String message) {
        txtLog.append(message + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlPackets = new javax.swing.JPanel();
        lblPackets = new javax.swing.JLabel();
        scpPackets = new javax.swing.JScrollPane();
        tblPackets = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 5 - UDP Server (DatagramSocket Ping-Pong)");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MÁY CHỦ UDP PING-PONG - DATAGRAMSOCKET / DATAGRAMPACKET");
        pnlControl.add(lblTitle);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlControl.add(lblPort);

        txtPort.setText("9191");
        txtPort.setToolTipText("Cổng UDP lắng nghe (mặc định 9191)");
        pnlControl.add(txtPort);

        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart.setText("Start Server");
        btnStart.setToolTipText("Khởi động UDPServer trên SwingWorker");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pnlControl.add(btnStart);

        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStop.setText("Stop Server");
        btnStop.setToolTipText("Dừng Server và đóng DatagramSocket");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        pnlControl.add(btnStop);

        btnClearLog.setText("Xóa Nhật Ký");
        btnClearLog.setToolTipText("Xóa toàn bộ dòng log và bảng gói tin");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        pnlControl.add(btnClearLog);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Chưa khởi động");
        pnlControl.add(lblStatus);

        progressBar.setString("Sẵn sàng");
        progressBar.setStringPainted(true);
        pnlControl.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ UDP SERVER (LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblPackets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPackets.setText("DANH SÁCH GÓI TIN UDP (DATAGRAM PACKETS):");

        tblPackets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Thời gian", "Source IP:Port", "Nội dung nhận", "Phản hồi gửi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPackets.setRowHeight(22);
        scpPackets.setViewportView(tblPackets);

        javax.swing.GroupLayout pnlPacketsLayout = new javax.swing.GroupLayout(pnlPackets);
        pnlPackets.setLayout(pnlPacketsLayout);
        pnlPacketsLayout.setHorizontalGroup(
            pnlPacketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacketsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPacketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpPackets)
                    .addGroup(pnlPacketsLayout.createSequentialGroup()
                        .addComponent(lblPackets)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPacketsLayout.setVerticalGroup(
            pnlPacketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacketsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPackets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpPackets, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPackets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPackets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien nut Start Server.
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        int port;

        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 1024 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Port hợp lệ (1025 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnStart.setEnabled(false);
        txtPort.setEnabled(false);
        btnStop.setEnabled(true);

        progressBar.setIndeterminate(true);
        progressBar.setString(String.format("Listening on UDP port %d...", port));
        lblStatus.setText(String.format("Trạng thái: Đang lắng nghe gói tin trên cổng %d...", port));

        // Khoi tao Server va gan Listener
        server = new UDPServer(port);
        server.setListener(new UDPServerListener() {
            @Override
            public void onLog(String message) {
                SwingUtilities.invokeLater(() -> appendLog(message));
            }

            @Override
            public void onServerStarted(int p) {
                SwingUtilities.invokeLater(() -> {
                    lblStatus.setText(String.format("Trạng thái: Đang lắng nghe trên cổng UDP %d...", p));
                    progressBar.setString(String.format("Listening on port %d...", p));
                    appendLog(String.format("-> [UDPServer] Khởi động thành công, lắng nghe DatagramPacket trên cổng: %d", p));
                });
            }

            @Override
            public void onPacketReceived(String clientAddress, int clientPort, String receivedMessage, String responseMessage) {
                SwingUtilities.invokeLater(() -> {
                    String timeStr = LocalTime.now().format(timeFormatter);
                    String sourceStr = clientAddress + ":" + clientPort;
                    packetCounter++;

                    // Ghi log theo dac ta
                    appendLog(String.format("Received: \"%s\" from %s -> Sent: \"%s\"", receivedMessage, sourceStr, responseMessage));

                    // Cap nhat vao JTable
                    DefaultTableModel model = (DefaultTableModel) tblPackets.getModel();
                    model.addRow(new Object[]{packetCounter, timeStr, sourceStr, receivedMessage, responseMessage});

                    progressBar.setString(String.format("Đã xử lý %d gói tin UDP", packetCounter));
                });
            }

            @Override
            public void onServerStopped() {
                SwingUtilities.invokeLater(() -> {
                    lblStatus.setText("Trạng thái: Đã dừng");
                    progressBar.setIndeterminate(false);
                    progressBar.setString("Đã dừng (Stopped)");
                    btnStart.setEnabled(true);
                    txtPort.setEnabled(true);
                    btnStop.setEnabled(false);
                    appendLog("-> [UDPServer] Đã dừng và đóng DatagramSocket an toàn.\n");
                });
            }
        });

        // Chay UDPServer trong SwingWorker de khong gay block UI
        serverWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                server.start();
                return null;
            }

            @Override
            protected void done() {
                lblStatus.setText("Trạng thái: Đã dừng");
                progressBar.setIndeterminate(false);
                progressBar.setString("Đã dừng");
                btnStart.setEnabled(true);
                txtPort.setEnabled(true);
                btnStop.setEnabled(false);
            }
        };

        serverWorker.execute();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * Xu ly su kien nut Stop Server.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        stopServer();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * Xu ly su kien nut Xoa Nhat Ky.
     */
    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtLog.setText("");
        DefaultTableModel model = (DefaultTableModel) tblPackets.getModel();
        model.setRowCount(0);
        packetCounter = 0;
        appendLog("-> Đã xóa sạch nhật ký và bảng gói tin UDP.\n");
    }//GEN-LAST:event_btnClearLogActionPerformed

    /**
     * Phuong thuc dung Server an toan.
     */
    private void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (serverWorker != null && !serverWorker.isDone()) {
            serverWorker.cancel(true);
        }
        btnStart.setEnabled(true);
        txtPort.setEnabled(true);
        btnStop.setEnabled(false);
        progressBar.setIndeterminate(false);
        progressBar.setString("Đã dừng");
        lblStatus.setText("Trạng thái: Đã dừng");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Look and Feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()) || "Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblPackets;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlPackets;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JScrollPane scpPackets;
    private javax.swing.JTable tblPackets;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
