package nhanh6;

import java.awt.Font;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien RMI Client (Stub proxy goi phuong thuc sayHello qua mang).
 *
 * Chuc nang chinh:
 * 1. Cau hinh dia chi Registry Host (localhost) va Port (1099).
 * 2. Nhap tham so ten (mac dinh: 'SinhVien') va thuc hien Remote Method Call.
 * 3. Hien thi phan hoi: "Remote says: Hello, <name>!" theo dung dac ta bao cao.
 * 4. Do luong thoi gian phan hoi khuu hoi (Round-trip time) tinh bang ms.
 * 5. Luu tru toan bo lich su goi tu xa vao JTable.
 */
public class ClientForm extends javax.swing.JFrame {

    private int callCounter = 0;
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblHistory.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblHistory.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblHistory.getColumnModel().getColumn(1).setPreferredWidth(90);
        tblHistory.getColumnModel().getColumn(2).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(3).setPreferredWidth(220);
        tblHistory.getColumnModel().getColumn(4).setPreferredWidth(110);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblHistory.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);

        txtLog.append("=== RMI CLIENT (GỌI PHƯƠNG THỨC TỪ XA) SẴN SÀNG ===\n");
        txtLog.append("- Cấu hình Registry Host, Port và Tên tham số (mặc định: 'SinhVien').\n");
        txtLog.append("- Bấm 'Gọi Remote Method' hoặc nhấn phím Enter để thực thi sayHello(name).\n");
        txtLog.append("- Stub sẽ tự động thực hiện Marshalling tham số, chuyển giao tới Skeleton của Server.\n");
        txtLog.append("- Nhận và hiển thị kết quả: Remote says: Hello, SinhVien!\n\n");
    }

    private void appendLog(String message) {
        txtLog.append(message + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfig = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        pnlAction = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCall = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlHistory = new javax.swing.JPanel();
        lblHistory = new javax.swing.JLabel();
        scpHistory = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 6 - RMI Client (Gọi Phương Thức Từ Xa)");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("RMI CLIENT - GỌI PHƯƠNG THỨC TU XA QUA RMI STUB");
        pnlConfig.add(lblTitle);

        lblHost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHost.setText("Registry Host:");
        pnlConfig.add(lblHost);

        txtHost.setText("localhost");
        txtHost.setToolTipText("Địa chỉ IP hoặc hostname máy chủ RMI Registry");
        pnlConfig.add(txtHost);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlConfig.add(lblPort);

        txtPort.setText("1099");
        txtPort.setToolTipText("Cổng RMI Registry (mặc định 1099)");
        pnlConfig.add(txtPort);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setText("Tên (tham số):");
        pnlAction.add(lblName);

        txtName.setText("SinhVien");
        txtName.setToolTipText("Nhập tên và nhấn Enter hoặc bấm Gọi Remote Method");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlAction.add(txtName);

        btnCall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCall.setText("Gọi Remote Method");
        btnCall.setToolTipText("Lookup 'HelloService' và gọi sayHello(name)");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });
        pnlAction.add(btnCall);

        btnClearLog.setText("Xóa Lịch Sử");
        btnClearLog.setToolTipText("Xóa nhật ký log và bảng lịch sử");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        pnlAction.add(btnClearLog);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Sẵn sàng");
        pnlAction.add(lblStatus);

        progressBar.setString("Sẵn sàng gọi RMI");
        progressBar.setStringPainted(true);
        pnlAction.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("KẾT QUẢ NHẬN TỪ SERVER (CLIENT LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHistory.setText("LỊCH SỬ GỌI PHƯƠNG THỨC TU XA (CALL HISTORY):");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Thời gian", "Tên gửi", "Kết quả nhận", "Thời gian (ms)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistory.setRowHeight(22);
        scpHistory.setViewportView(tblHistory);

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpHistory)
                    .addGroup(pnlHistoryLayout.createSequentialGroup()
                        .addComponent(lblHistory)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien khi nhan Enter tren txtName.
     */
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        executeRemoteCall();
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * Xu ly su kien nut Goi Remote Method.
     */
    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        executeRemoteCall();
    }//GEN-LAST:event_btnCallActionPerformed

    /**
     * Xu ly su kien nut Xoa Lich Su.
     */
    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtLog.setText("");
        DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
        model.setRowCount(0);
        callCounter = 0;
        appendLog("-> Đã xóa sạch nhật ký log và lịch sử gọi phương thức từ xa.\n");
    }//GEN-LAST:event_btnClearLogActionPerformed

    /**
     * Thuc thi goi phuong thuc sayHello tren SwingWorker.
     */
    private void executeRemoteCall() {
        String host = txtHost.getText().trim();
        if (host.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ Registry Host!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int port;
        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port phải nằm trong khoảng (1 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String name = txtName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tham số!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        btnCall.setEnabled(false);
        txtName.setEnabled(false);
        progressBar.setIndeterminate(true);
        progressBar.setString("Đang tra cứu Registry & gọi sayHello()...");
        lblStatus.setText(String.format("Trạng thái: Đang kết nối tới %s:%d...", host, port));

        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            private long elapsed = 0;
            private String timeStr = "";

            @Override
            protected String doInBackground() throws Exception {
                timeStr = LocalTime.now().format(timeFormatter);

                // 1. Ket noi Registry
                Registry registry = LocateRegistry.getRegistry(host, port);

                // 2. Tra cuu Stub tu Registry
                HelloInterface stub = (HelloInterface) registry.lookup(RMIServer.SERVICE_NAME);

                // 3. Do thoi gian goi ham tu xa
                long t0 = System.currentTimeMillis();
                String response = stub.sayHello(name);
                elapsed = System.currentTimeMillis() - t0;

                return response;
            }

            @Override
            protected void done() {
                try {
                    String result = get();
                    callCounter++;

                    // In theo dung dac ta: Remote says: Hello, SinhVien!
                    appendLog("Remote says: " + result);
                    appendLog(String.format("-> [RMI Call #%d] Tham số: \"%s\" | Phản hồi: \"%s\" (%d ms)\n",
                            callCounter, name, result, elapsed));

                    // Cap nhat JTable: Ten gui | Ket qua nhan | Thoi gian (ms)
                    DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
                    model.addRow(new Object[]{callCounter, timeStr, name, result, elapsed});

                    lblStatus.setText(String.format("Trạng thái: Hoàn tất (%d ms) - %s", elapsed, result));
                    progressBar.setString("Gọi thành công");

                } catch (Exception e) {
                    String err = e.getCause() != null ? e.getCause().getMessage() : e.getMessage();
                    appendLog("[Lỗi RMI] " + err);
                    appendLog("-> Gợi ý: Hãy đảm bảo RMIServer đã được khởi động trên cổng " + port + " và service 'HelloService' đã được đăng ký.\n");

                    callCounter++;
                    String timeNow = LocalTime.now().format(timeFormatter);
                    DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
                    model.addRow(new Object[]{callCounter, timeNow, name, "[Lỗi] " + err, elapsed});

                    lblStatus.setText("Trạng thái: Lỗi kết nối RMI!");
                    progressBar.setString("Thất bại");
                } finally {
                    progressBar.setIndeterminate(false);
                    btnCall.setEnabled(true);
                    txtName.setEnabled(true);
                    txtName.requestFocusInWindow();
                    txtName.selectAll();
                }
            }
        };

        worker.execute();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Look and Feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()) || "Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCall;
    private javax.swing.JButton btnClearLog;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAction;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpHistory;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
