package nhanh6;

import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien RMI Server (Stub / Skeleton / RMI Registry).
 *
 * Chuc nang chinh:
 * 1. Khoi tao RMI Registry tai cong 1099 (hoac cong tuy chon).
 * 2. Dang ky Remote Object (HelloImpl) vao Registry voi ten 'HelloService'.
 * 3. Hien thi truc quan pipeline RMI khi co loi goi ham tu xa tu Client:
 *    -> [Buoc 1: Stub]     Marshalling tham so
 *    -> [Buoc 2: Skeleton] Unmarshalling thanh cong
 *    -> [Buoc 3: Server]   HelloImpl.sayHello() thuc thi
 *    ==> Thu tu xu ly: Stub -> Skeleton -> HelloImpl.sayHello()
 * 4. Luu tru toan bo cac luot goi tu xa vao JTable.
 * 5. Dung Server, unbind va giai phong cong TCP an toan.
 */
public class ServerForm extends javax.swing.JFrame {

    private Registry registry;
    private HelloImpl helloService;
    private boolean isRegistryCreatedLocally = false;
    private int callCounter = 0;
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblCalls.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblCalls.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblCalls.getColumnModel().getColumn(1).setPreferredWidth(90);
        tblCalls.getColumnModel().getColumn(2).setPreferredWidth(140);
        tblCalls.getColumnModel().getColumn(3).setPreferredWidth(160);
        tblCalls.getColumnModel().getColumn(4).setPreferredWidth(200);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblCalls.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblCalls.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);

        // Xu ly su kien khi dong Form thi dung Server an toan
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                stopServer();
            }
        });

        txtLog.append("=== RMI SERVER (STUB / SKELETON / REGISTRY) SẴN SÀNG ===\n");
        txtLog.append("- Cấu hình cổng RMI Registry (mặc định: 1099).\n");
        txtLog.append("- Bấm 'Start Registry' để khởi tạo Registry và đăng ký service 'HelloService'.\n");
        txtLog.append("- Khi Client gọi phương thức từ xa sayHello(), Server hiển thị chi tiết Pipeline RMI.\n");
        txtLog.append("- Bấm 'Stop Server' để unbind service và đóng cổng Registry an toàn.\n\n");
    }

    private void appendLog(String message) {
        txtLog.append(message + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlCalls = new javax.swing.JPanel();
        lblCalls = new javax.swing.JLabel();
        scpCalls = new javax.swing.JScrollPane();
        tblCalls = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 6 - RMI Server (Stub / Skeleton / Registry)");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("RMI SERVER - STUB, SKELETON & RMI REGISTRY");
        pnlControl.add(lblTitle);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Registry Port:");
        pnlControl.add(lblPort);

        txtPort.setText("1099");
        txtPort.setToolTipText("Cổng RMI Registry (mặc định 1099)");
        pnlControl.add(txtPort);

        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart.setText("Start Registry");
        btnStart.setToolTipText("Khởi động RMI Registry và bind Remote Object");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pnlControl.add(btnStart);

        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStop.setText("Stop Server");
        btnStop.setToolTipText("Hủy đăng ký (unbind) và dừng Registry");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        pnlControl.add(btnStop);

        btnClearLog.setText("Xóa Nhật Ký");
        btnClearLog.setToolTipText("Xóa toàn bộ dòng log và bảng lịch sử");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        pnlControl.add(btnClearLog);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Chưa khởi động");
        pnlControl.add(lblStatus);

        progressBar.setString("Sẵn sàng");
        progressBar.setStringPainted(true);
        pnlControl.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("LOG – RMI PIPELINE (Stub → Skeleton → HelloImpl):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCalls.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCalls.setText("DANH SÁCH LƯỢT GỌI PHƯƠNG THỨC TỪ XA (REMOTE METHOD CALLS):");

        tblCalls.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Thời gian", "Client Host", "Tham số (name)", "Kết quả trả về"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCalls.setRowHeight(22);
        scpCalls.setViewportView(tblCalls);

        javax.swing.GroupLayout pnlCallsLayout = new javax.swing.GroupLayout(pnlCalls);
        pnlCalls.setLayout(pnlCallsLayout);
        pnlCallsLayout.setHorizontalGroup(
            pnlCallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCallsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpCalls)
                    .addGroup(pnlCallsLayout.createSequentialGroup()
                        .addComponent(lblCalls)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCallsLayout.setVerticalGroup(
            pnlCallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCallsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpCalls, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCalls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien nut Start Registry.
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        int port;

        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 1024 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Port hợp lệ (1025 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnStart.setEnabled(false);
        txtPort.setEnabled(false);
        btnStop.setEnabled(true);

        progressBar.setIndeterminate(true);
        progressBar.setString(String.format("Starting RMI Registry on port %d...", port));
        lblStatus.setText(String.format("Trạng thái: Đang khởi tạo Registry trên cổng %d...", port));

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    registry = LocateRegistry.createRegistry(port);
                    isRegistryCreatedLocally = true;
                    appendLog(String.format("-> [RMI Server] Đã tạo mới RMI Registry trên cổng TCP: %d", port));
                } catch (RemoteException e) {
                    registry = LocateRegistry.getRegistry(port);
                    isRegistryCreatedLocally = false;
                    appendLog(String.format("-> [RMI Server] Đã kết nối tới RMI Registry hiện có trên cổng TCP: %d", port));
                }

                // Khoi tao Remote Object kem listener
                helloService = new HelloImpl(new RMIServerListener() {
                    @Override
                    public void onLog(String message) {
                        SwingUtilities.invokeLater(() -> appendLog(message));
                    }

                    @Override
                    public void onRegistryStarted(int p) {
                    }

                    @Override
                    public void onServiceBound(String serviceName) {
                    }

                    @Override
                    public void onRemoteCall(String clientHost, String paramName, String result) {
                        SwingUtilities.invokeLater(() -> {
                            callCounter++;
                            String timeStr = LocalTime.now().format(timeFormatter);

                            // In pipeline 3 buoc theo dung dac ta bao cao cuoi ky
                            appendLog("\n-------------------------------------------------------------");
                            appendLog(String.format("[Lượt #%d] Remote Call từ Client [%s]: sayHello(\"%s\")", callCounter, clientHost, paramName));
                            appendLog(String.format("-> [Buoc 1: Stub]     Marshalling tham so: \"%s\"", paramName));
                            appendLog("-> [Buoc 2: Skeleton] Unmarshalling thanh cong");
                            appendLog(String.format("-> [Buoc 3: Server]   HelloImpl.sayHello() thuc thi -> \"%s\"", result));
                            appendLog("==> Thu tu: Stub -> Skeleton -> HelloImpl.sayHello()");
                            appendLog("-------------------------------------------------------------");

                            // Cap nhat vao JTable
                            DefaultTableModel model = (DefaultTableModel) tblCalls.getModel();
                            model.addRow(new Object[]{callCounter, timeStr, clientHost, paramName, result});

                            progressBar.setString(String.format("Đã phục vụ %d lượt gọi RMI", callCounter));
                        });
                    }

                    @Override
                    public void onServiceUnbound(String serviceName) {
                    }

                    @Override
                    public void onServerStopped() {
                    }
                });

                // Dang ky service vao Registry
                registry.rebind(RMIServer.SERVICE_NAME, helloService);
                appendLog(String.format("-> [RMI Server] Đã đăng ký (bind) service '%s' thành công vào Registry.", RMIServer.SERVICE_NAME));
                appendLog("-> [RMI Server] Sẵn sàng nhận lời gọi phương thức từ xa (Waiting for remote calls...)\n");

                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    lblStatus.setText(String.format("Trạng thái: Đang lắng nghe RMI trên cổng %d", port));
                    progressBar.setIndeterminate(false);
                    progressBar.setString("Waiting for remote calls...");
                } catch (Exception e) {
                    String err = e.getCause() != null ? e.getCause().getMessage() : e.getMessage();
                    JOptionPane.showMessageDialog(ServerForm.this, "Lỗi khởi động RMI Server: " + err, "Lỗi", JOptionPane.ERROR_MESSAGE);
                    stopServer();
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * Xu ly su kien nut Stop Server.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        stopServer();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * Xu ly su kien nut Xoa Nhat Ky.
     */
    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtLog.setText("");
        DefaultTableModel model = (DefaultTableModel) tblCalls.getModel();
        model.setRowCount(0);
        callCounter = 0;
        appendLog("-> Đã xóa sạch nhật ký và bảng danh sách lượt gọi từ xa.\n");
    }//GEN-LAST:event_btnClearLogActionPerformed

    /**
     * Phuong thuc dung Server an toan va giai phong Registry port.
     */
    private void stopServer() {
        try {
            if (registry != null) {
                try {
                    registry.unbind(RMIServer.SERVICE_NAME);
                    appendLog(String.format("-> [RMI Server] Đã hủy đăng ký (unbind) '%s' khỏi Registry.", RMIServer.SERVICE_NAME));
                } catch (Exception ignored) {}
            }

            if (helloService != null) {
                try {
                    UnicastRemoteObject.unexportObject(helloService, true);
                    appendLog("-> [RMI Server] Đã unexport Remote Object HelloImpl.");
                } catch (Exception ignored) {}
                helloService = null;
            }

            if (registry != null && isRegistryCreatedLocally) {
                try {
                    UnicastRemoteObject.unexportObject(registry, true);
                    appendLog("-> [RMI Server] Đã đóng RMI Registry và giải phóng cổng TCP.");
                } catch (Exception ignored) {}
                registry = null;
            }

            appendLog("-> [RMI Server] Server đã dừng hoàn toàn.\n");

        } catch (Exception e) {
            appendLog("[Lỗi khi dừng] " + e.getMessage());
        } finally {
            btnStart.setEnabled(true);
            txtPort.setEnabled(true);
            btnStop.setEnabled(false);
            progressBar.setIndeterminate(false);
            progressBar.setString("Đã dừng (Stopped)");
            lblStatus.setText("Trạng thái: Đã dừng");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Look and Feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()) || "Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblCalls;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCalls;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpCalls;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JTable tblCalls;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
