package nhanh2;

import java.awt.Component;
import java.awt.Font;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien do hoa (GUI) truc quan cho Nhanh 2:
 * Benchmark so sanh sao chep tep giua Unbuffered Stream va Buffered Stream.
 *
 * Chuc nang:
 * 1. Chon file nguon dung luong lon (khuyen nghi >= 5 MB) hoac tu sinh file 5 MB.
 * 2. Do thoi gian sao chep bang SwingWorker chay tren background thread.
 * 3. Chuyen huong Console log vao JTextArea realtime (kem bieu do ASCII Bar Chart).
 * 4. Cap nhat bang JTable tong hop: Phuong phap, Thoi gian (ms), Toc do (MB/s).
 */
public class BenchmarkForm extends javax.swing.JFrame {

    private SwingWorker<Void, String> benchmarkWorker;
    private long measuredUnbufferedTime = -1;
    private long measuredBufferedTime = -1;

    /**
     * Creates new form BenchmarkForm
     */
    public BenchmarkForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap bo sung sau khi khoi tao giao dien initComponents().
     */
    private void customInit() {
        // Can giua man hinh
        setLocationRelativeTo(null);

        // Tim file mau mac dinh
        File defaultFile = new File("src/nhanh2/benchmark_source_5mb.dat");
        if (defaultFile.exists()) {
            txtFilePath.setText(defaultFile.getAbsolutePath());
        } else {
            File altFile = new File("src/nhanh1/sample.txt");
            if (altFile.exists()) {
                txtFilePath.setText(altFile.getAbsolutePath());
            } else {
                txtFilePath.setText("src/nhanh2/benchmark_source_5mb.dat");
            }
        }

        // Dinh dang bang ket qua
        tblResult.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblResult.getColumnModel().getColumn(0).setPreferredWidth(260);
        tblResult.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblResult.getColumnModel().getColumn(2).setPreferredWidth(180);

        // Can giua cot Thoi gian va Toc do
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblResult.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblResult.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

        // Thong bao khoi dong
        txtLog.append("=== CHUONG TRINH BENCHMARK: BUFFERED VS UNBUFFERED STREAM ===\n");
        txtLog.append("- Khuyến nghị: Sử dụng tệp có dung lượng từ 1 MB đến 10 MB để thấy rõ sự khác biệt.\n");
        txtLog.append("- Nếu tệp 5 MB chưa tồn tại, hệ thống sẽ tự động khởi tạo khi bấm 'Chạy Benchmark'.\n");
        txtLog.append("- Tác vụ sao chép chạy trên SwingWorker đảm bảo giao diện phản hồi mượt mà.\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnChooseFile = new javax.swing.JButton();
        txtFilePath = new javax.swing.JTextField();
        btnRun = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        scpResult = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 2 - Benchmark Buffered vs Unbuffered Copy");
        setMinimumSize(new java.awt.Dimension(720, 600));
        setPreferredSize(new java.awt.Dimension(780, 650));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("BENCHMARK HIỆU NĂNG: BUFFERED VS UNBUFFERED STREAM");
        pnlControl.add(lblTitle);

        btnChooseFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChooseFile.setText("Chọn File Nguồn...");
        btnChooseFile.setToolTipText("Chọn tệp tin nguồn dung lượng lớn (>= 5 MB)");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });
        pnlControl.add(btnChooseFile);

        txtFilePath.setEditable(false);
        txtFilePath.setToolTipText("Đường dẫn file nguồn benchmark");
        pnlControl.add(txtFilePath);

        btnRun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRun.setText("Chạy Benchmark");
        btnRun.setToolTipText("Bắt đầu quá trình sao chép và đo lường tốc độ");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        pnlControl.add(btnRun);

        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStop.setText("Dừng");
        btnStop.setToolTipText("Huỷ benchmark đang chạy");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        pnlControl.add(btnStop);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Sŕn sàng");
        pnlControl.add(lblStatus);

        progressBar.setString("");
        progressBar.setStringPainted(true);
        pnlControl.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ THỰC THI (LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResult.setText("KẾT QUẢ BENCHMARK:");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Unbuffered (FileInputStream / FileOutputStream)", null, null},
                {"Buffered (BufferedInputStream / BufferedOutputStream)", null, null}
            },
            new String [] {
                "Phương pháp", "Thời gian (ms)", "Tốc độ (MB/s)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResult.setRowHeight(24);
        scpResult.setViewportView(tblResult);

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpResult)
                    .addGroup(pnlResultLayout.createSequentialGroup()
                        .addComponent(lblResult)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpResult, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien nut Chon File Nguon.
     */
    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn tệp nguồn dung lượng lớn (>= 5 MB)");

        File current = new File(txtFilePath.getText().trim());
        if (current.exists()) {
            chooser.setSelectedFile(current);
        } else {
            chooser.setCurrentDirectory(new File("src/nhanh2"));
        }

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selected = chooser.getSelectedFile();
            txtFilePath.setText(selected.getAbsolutePath());
            double sizeMB = selected.length() / (1024.0 * 1024.0);
            txtLog.append(String.format("-> [Hệ thống] Đã chọn tệp: %s (%,d bytes ~ %.2f MB)\n",
                    selected.getName(), selected.length(), sizeMB));
            lblStatus.setText(String.format("Trạng thái: Đã chọn %s (%.2f MB)", selected.getName(), sizeMB));
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed

    /**
     * Xu ly su kien nut Chay Benchmark.
     */
    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        final String filePath = txtFilePath.getText().trim();
        if (filePath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đường dẫn tệp nguồn!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        File targetFile = new File(filePath);
        if (!targetFile.exists()) {
            // Neu file 5MB chua ton tai, tu dong sinh file
            if (filePath.contains("benchmark_source_5mb") || filePath.endsWith(".dat")) {
                try {
                    BenchmarkRunner.generateLargeFile(filePath, 5);
                    targetFile = new File(filePath);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Không thể khởi tạo tệp benchmark 5 MB: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tệp tin không tồn tại: " + filePath, "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Cap nhat trang thai UI
        btnRun.setEnabled(false);
        btnChooseFile.setEnabled(false);
        btnStop.setEnabled(true);
        progressBar.setIndeterminate(true);
        progressBar.setString("Đang thực hiện benchmark sao chép...");
        lblStatus.setText("Trạng thái: Đang thực thi benchmark...");

        // Reset bang ket qua
        DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
        model.setValueAt("-", 0, 1);
        model.setValueAt("-", 0, 2);
        model.setValueAt("-", 1, 1);
        model.setValueAt("-", 1, 2);

        final File sourceFile = targetFile;
        final double sizeMB = (double) sourceFile.length() / (1024.0 * 1024.0);

        txtLog.append("\n=================================================================\n");
        txtLog.append("BẮT ĐẦU BENCHMARK: BUFFERED VS UNBUFFERED STREAM\n");
        txtLog.append(String.format("Tệp nguồn: %s (%,d bytes ~ %.2f MB)\n",
                sourceFile.getAbsolutePath(), sourceFile.length(), sizeMB));
        txtLog.append("=================================================================\n");

        // File dich tam thoi
        final File destUnbuffered = new File("src/nhanh2/temp_unbuffered_out.dat");
        final File destBuffered = new File("src/nhanh2/temp_buffered_out.dat");

        // SwingWorker thuc thi blocking IO tren background thread
        benchmarkWorker = new SwingWorker<Void, String>() {
            private long unbufferedMs = -1;
            private long bufferedMs = -1;
            private double speedUnbuffered = 0.0;
            private double speedBuffered = 0.0;
            private double speedupFactor = 0.0;
            private PrintStream oldOut;
            private PrintStream oldErr;

            @Override
            protected Void doInBackground() throws Exception {
                // Chuyen huong System.out va System.err vao SwingWorker log
                oldOut = System.out;
                oldErr = System.err;
                PrintStream customOut = new PrintStream(new OutputStream() {
                    private ByteArrayOutputStream baos = new ByteArrayOutputStream();

                    @Override
                    public void write(int b) {
                        if (b == '\n') {
                            String line = baos.toString(StandardCharsets.UTF_8);
                            publish(line);
                            baos.reset();
                        } else {
                            baos.write(b);
                        }
                    }
                }, true, StandardCharsets.UTF_8);

                System.setOut(customOut);
                System.setErr(customOut);

                try {
                    // Buoc 1: Unbuffered Copy
                    publish("[BƯỚC 1/2] Đang sao chép KHÔNG dùng bộ đệm (UnbufferedCopy)...");
                    unbufferedMs = UnbufferedCopy.copyAndMeasure(sourceFile, destUnbuffered);
                    speedUnbuffered = (unbufferedMs > 0) ? (sizeMB / (unbufferedMs / 1000.0)) : 0.0;
                    publish(String.format("-> [Unbuffered] Hoàn tất: %,d ms | Tốc độ: %.2f MB/s", unbufferedMs, speedUnbuffered));

                    if (isCancelled()) {
                        return null;
                    }

                    // Buoc 2: Buffered Copy
                    publish("\n[BƯỚC 2/2] Đang sao chép CÓ dùng bộ đệm (BufferedCopy 8 KB RAM)...");
                    bufferedMs = BufferedCopy.copyAndMeasure(sourceFile, destBuffered);
                    speedBuffered = (bufferedMs > 0) ? (sizeMB / (bufferedMs / 1000.0)) : 0.0;
                    speedupFactor = (bufferedMs > 0) ? ((double) unbufferedMs / bufferedMs) : 0.0;
                    publish(String.format("-> [Buffered]   Hoàn tất: %,d ms | Tốc độ: %.2f MB/s", bufferedMs, speedBuffered));

                    if (isCancelled()) {
                        return null;
                    }

                    // Buoc 3: Bang so sanh & Bieu do ASCII
                    BenchmarkRunner.printComparisonTable(sourceFile.length(), unbufferedMs * 1_000_000L, bufferedMs * 1_000_000L);
                    BenchmarkRunner.printAsciiCharts(unbufferedMs * 1_000_000L, bufferedMs * 1_000_000L, sourceFile.length());
                    //BenchmarkRunner.printTechnicalAnalysis(unbufferedMs * 1_000_000L, bufferedMs * 1_000_000L);

                } finally {
                    System.setOut(oldOut);
                    System.setErr(oldErr);

                    // Don dep cac tep dich tam thoi
                    if (destUnbuffered.exists()) {
                        destUnbuffered.delete();
                    }
                    if (destBuffered.exists()) {
                        destBuffered.delete();
                    }
                }

                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                for (String chunk : chunks) {
                    txtLog.append(chunk + "\n");
                }
                txtLog.setCaretPosition(txtLog.getDocument().getLength());
            }

            @Override
            protected void done() {
                btnRun.setEnabled(true);
                btnChooseFile.setEnabled(true);
                btnStop.setEnabled(false);
                progressBar.setIndeterminate(false);

                if (isCancelled()) {
                    progressBar.setValue(0);
                    progressBar.setString("Đã huỷ");
                    lblStatus.setText("Trạng thái: Benchmark đã bị huỷ bởi người dùng");
                    txtLog.append("\n[HỆ THỐNG] Quá trình benchmark đã dừng theo yêu cầu!\n");
                } else {
                    progressBar.setValue(100);
                    progressBar.setString("Hoàn tất 100%");
                    lblStatus.setText("Trạng thái: Hoàn tất benchmark");

                    measuredUnbufferedTime = unbufferedMs;
                    measuredBufferedTime = bufferedMs;

                    // Cap nhat bang ket qua
                    DefaultTableModel resModel = (DefaultTableModel) tblResult.getModel();
                    resModel.setValueAt(unbufferedMs + " ms", 0, 1);
                    resModel.setValueAt(String.format("%.2f MB/s", speedUnbuffered), 0, 2);

                    resModel.setValueAt(bufferedMs + " ms", 1, 1);
                    resModel.setValueAt(String.format("%.2f MB/s (Gấp %.1fx)", speedBuffered, speedupFactor), 1, 2);

                    txtLog.append(String.format("\n[HỆ THỐNG] Hoàn tất! Buffered Stream giúp tăng tốc gấp %.1f lần so với Unbuffered Stream.\n", speedupFactor));
                }
            }
        };

        benchmarkWorker.execute();
    }//GEN-LAST:event_btnRunActionPerformed

    /**
     * Xu ly su kien nut Dung.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (benchmarkWorker != null && !benchmarkWorker.isDone()) {
            benchmarkWorker.cancel(true);
            txtLog.append("-> [Hệ thống] Đang gửi yêu cầu huỷ benchmark worker...\n");
        }
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(BenchmarkForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BenchmarkForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JScrollPane scpResult;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
