package nhanh3;

import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 * Giao dien TCP Client gui chuoi va nhan chuoi dao nguoc tu MultiThreadedServer.
 *
 * Chuc nang:
 * 1. Gui chuoi don le bang nut Send hoac nhan Enter.
 * 2. Nhan ket qua chuoi dao nguoc tu ThreadPool cua Server.
 * 3. Gia lap 5 Client ket noi dong thoi de kiem tra tinh da luong cua Server.
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien sau khi khoi tao components.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        txtLog.append("=== TCP CLIENT - GIAO DIỆN TRUYỀN NHẬN CHUỖI ===\n");
        txtLog.append("- Nhập địa chỉ Server Host, Port và chuỗi ký tự cần gửi.\n");
        txtLog.append("- Bấm 'Gửi (Send)' hoặc nhấn phím Enter để truyền nhận qua Socket TCP.\n");
        txtLog.append("- Bấm 'Giả Lập 5 Clients' để kiểm thử tính năng ThreadPool phục vụ đồng thời.\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfig = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnSimulate = new javax.swing.JButton();
        pnlMessage = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 3 - TCP Client (Kiểm Thử Server Đa Luồng)");
        setMinimumSize(new java.awt.Dimension(650, 520));
        setPreferredSize(new java.awt.Dimension(700, 560));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TCP CLIENT - GỬI CHUỖI VÀ NHẬN KẾT QUẢ ĐẢO NGƯỢC");
        pnlConfig.add(lblTitle);

        lblHost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHost.setText("Server Host:");
        pnlConfig.add(lblHost);

        txtHost.setText("localhost");
        txtHost.setToolTipText("Địa chỉ IP hoặc hostname của Server");
        pnlConfig.add(txtHost);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlConfig.add(lblPort);

        txtPort.setText("8080");
        txtPort.setToolTipText("Cổng Server");
        pnlConfig.add(txtPort);

        btnSimulate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimulate.setText("Giả Lập 5 Clients");
        btnSimulate.setToolTipText("Kiểm thử 5 Client gửi đồng thời vào ThreadPool");
        btnSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulateActionPerformed(evt);
            }
        });
        pnlConfig.add(btnSimulate);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMessage.setText("Chuỗi gửi:");
        pnlMessage.add(lblMessage);

        txtMessage.setText("hello world");
        txtMessage.setToolTipText("Nhập chuỗi và nhấn Enter hoặc bấm Gửi");
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        pnlMessage.add(txtMessage);

        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setText("Gửi (Send)");
        btnSend.setToolTipText("Gửi chuỗi tới Server để đảo ngược");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        pnlMessage.add(btnSend);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ TRUYỀN NHẬN (LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly khi nhan Enter trong txtMessage.
     */
    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        sendMessage();
    }//GEN-LAST:event_txtMessageActionPerformed

    /**
     * Xu ly su kien nut Gui (Send).
     */
    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        sendMessage();
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * Xu ly su kien nut Gia Lap 5 Clients song song.
     */
    private void btnSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulateActionPerformed
        final String host = txtHost.getText().trim();
        final int port;
        try {
            port = Integer.parseInt(txtPort.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnSend.setEnabled(false);
        btnSimulate.setEnabled(false);
        txtLog.append(String.format("\n>>> BẮT ĐẦU GIẢ LẬP 5 CLIENT KẾT NỐI ĐỒNG THỜI (%s:%d) <<<\n", host, port));

        SwingWorker<Void, String> simWorker = new SwingWorker<Void, String>() {
            private PrintStream oldOut;
            private PrintStream oldErr;

            @Override
            protected Void doInBackground() throws Exception {
                oldOut = System.out;
                oldErr = System.err;

                PrintStream customOut = new PrintStream(new OutputStream() {
                    private ByteArrayOutputStream baos = new ByteArrayOutputStream();

                    @Override
                    public void write(int b) {
                        if (b == '\n') {
                            String line = baos.toString(StandardCharsets.UTF_8);
                            publish(line);
                            baos.reset();
                        } else {
                            baos.write(b);
                        }
                    }
                }, true, StandardCharsets.UTF_8);

                System.setOut(customOut);
                System.setErr(customOut);

                try {
                    TestClient.runConcurrentSimulation(host, port, 5);
                } finally {
                    System.setOut(oldOut);
                    System.setErr(oldErr);
                }
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                for (String chunk : chunks) {
                    txtLog.append(chunk + "\n");
                }
                txtLog.setCaretPosition(txtLog.getDocument().getLength());
            }

            @Override
            protected void done() {
                btnSend.setEnabled(true);
                btnSimulate.setEnabled(true);
                txtLog.append(">>> HOÀN TẤT ĐỢT GIẢ LẬP ĐỒNG THỜI <<<\n\n");
                txtLog.setCaretPosition(txtLog.getDocument().getLength());
            }
        };

        simWorker.execute();
    }//GEN-LAST:event_btnSimulateActionPerformed

    /**
     * Gui message don le toi server.
     */
    private void sendMessage() {
        final String host = txtHost.getText().trim();
        final String message = txtMessage.getText().trim();

        if (host.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ Server Host!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chuỗi cần gửi!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        final int port;
        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnSend.setEnabled(false);
        txtLog.append(String.format("-> [Client] Gửi: \"%s\"\n", message));

        SwingWorker<String, Void> sendWorker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                return TestClient.sendAndReceive(host, port, message);
            }

            @Override
            protected void done() {
                btnSend.setEnabled(true);
                try {
                    String response = get();
                    txtLog.append(String.format("<- [Server] Nhận chuỗi đảo ngược: \"%s\"\n\n", response));
                    txtMessage.selectAll();
                    txtMessage.requestFocus();
                } catch (Exception e) {
                    String errorMsg = (e.getCause() != null) ? e.getCause().getMessage() : e.getMessage();
                    txtLog.append(String.format("Lỗi kết nối Server (%s:%d): %s\n\n", host, port, errorMsg));
                    JOptionPane.showMessageDialog(ClientForm.this,
                            String.format("Không thể kết nối tới Server tại %s:%d\nChi tiết: %s", host, port, errorMsg),
                            "Lỗi Kết Nối Socket", JOptionPane.ERROR_MESSAGE);
                }
                txtLog.setCaretPosition(txtLog.getDocument().getLength());
            }
        };

        sendWorker.execute();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSimulate;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
