package nhanh3;

import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien Server TCP Da Luong (Multithreaded Server) su dung ThreadPool.
 *
 * Chuc nang:
 * 1. Cau hinh cong Port va so luong Worker Threads trong ThreadPool.
 * 2. Start/Stop Server an toan tren SwingWorker khong gay treo giao dien.
 * 3. Hien thi danh sach Client ket noi truc tiep vao JTable realtime.
 * 4. Log chi tiet chuoi nhan va chuoi dao nguoc gui tra ve cho Client.
 */
public class ServerForm extends javax.swing.JFrame {

    private MultiThreadedServer server;
    private SwingWorker<Void, Void> serverWorker;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblClients.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblClients.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblClients.getColumnModel().getColumn(1).setPreferredWidth(220);
        tblClients.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblClients.getColumnModel().getColumn(3).setPreferredWidth(160);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblClients.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblClients.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblClients.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);

        // Xu ly su kien khi dong Form thi dung Server
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                stopServer();
            }
        });

        txtLog.append("=== MÁY CHỦ TCP ĐA LUỒNG (THREADPOOL) SẴN SÀNG ===\n");
        txtLog.append("- Cấu hình Port và kích thước ThreadPool (số luồng worker tối đa).\n");
        txtLog.append("- Nhấn 'Start Server' để bắt đầu lắng nghe kết nối từ Client.\n");
        txtLog.append("- Nhấn 'Stop Server' để đóng cổng và giải phóng tài nguyên luồng an toàn.\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        lblPoolSize = new javax.swing.JLabel();
        txtPoolSize = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlClients = new javax.swing.JPanel();
        lblClients = new javax.swing.JLabel();
        scpClients = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 3 - TCP Server Đa Luồng (ThreadPool)");
        setMinimumSize(new java.awt.Dimension(750, 620));
        setPreferredSize(new java.awt.Dimension(800, 660));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MÁY CHỦ TCP ĐA LUỒNG - MULTITHREADED SERVER (THREADPOOL)");
        pnlControl.add(lblTitle);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlControl.add(lblPort);

        txtPort.setText("8080");
        txtPort.setToolTipText("Cổng TCP lắng nghe");
        pnlControl.add(txtPort);

        lblPoolSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPoolSize.setText("Pool size:");
        pnlControl.add(lblPoolSize);

        txtPoolSize.setText("5");
        txtPoolSize.setToolTipText("Số lượng thread worker trong ThreadPool");
        pnlControl.add(txtPoolSize);

        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart.setText("Start Server");
        btnStart.setToolTipText("Khởi động Server TCP trên SwingWorker");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pnlControl.add(btnStart);

        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStop.setText("Stop Server");
        btnStop.setToolTipText("Dừng Server và giải phóng ThreadPool");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        pnlControl.add(btnStop);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Sẵn sàng");
        pnlControl.add(lblStatus);

        progressBar.setString("");
        progressBar.setStringPainted(true);
        pnlControl.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ MÁY CHỦ (LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblClients.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClients.setText("DANH SÁCH CLIENT KẾT NỐI:");

        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "IP Address", "Thời gian", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClients.setRowHeight(22);
        scpClients.setViewportView(tblClients);

        javax.swing.GroupLayout pnlClientsLayout = new javax.swing.GroupLayout(pnlClients);
        pnlClients.setLayout(pnlClientsLayout);
        pnlClientsLayout.setHorizontalGroup(
            pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpClients)
                    .addGroup(pnlClientsLayout.createSequentialGroup()
                        .addComponent(lblClients)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlClientsLayout.setVerticalGroup(
            pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpClients, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien nut Start Server.
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        int port;
        int poolSize;

        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 1024 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Port hợp lệ (1025 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            poolSize = Integer.parseInt(txtPoolSize.getText().trim());
            if (poolSize <= 0 || poolSize > 200) {
                JOptionPane.showMessageDialog(this, "Pool size phải nằm trong khoảng từ 1 đến 200!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pool size phải là số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnStart.setEnabled(false);
        txtPort.setEnabled(false);
        txtPoolSize.setEnabled(false);
        btnStop.setEnabled(true);

        progressBar.setIndeterminate(true);
        progressBar.setString(String.format("Server RUNNING on port %d (Pool: %d)", port, poolSize));
        lblStatus.setText(String.format("Trạng thái: Đang lắng nghe trên cổng %d...", port));

        // Khoi tao va gan Listener cho Server
        server = new MultiThreadedServer(port, poolSize);
        server.setListener(new ServerListener() {
            @Override
            public void onLog(String message) {
                SwingUtilities.invokeLater(() -> appendLog(message));
            }

            @Override
            public void onServerStarted(int p, int pool) {
                SwingUtilities.invokeLater(() -> {
                    lblStatus.setText(String.format("Trạng thái: Đang lắng nghe trên cổng %d (Pool: %d threads)", p, pool));
                    appendLog(String.format("-> [Server] Đã khởi động trên cổng %d với ThreadPool %d luồng worker.", p, pool));
                });
            }

            @Override
            public void onClientConnected(int clientId, String clientAddress, String connectTime) {
                SwingUtilities.invokeLater(() -> {
                    DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
                    model.addRow(new Object[]{clientId, clientAddress, connectTime, "Đang xử lý"});
                    appendLog(String.format("[Main-Server] Chấp nhận Client #%d từ %s lúc %s", clientId, clientAddress, connectTime));
                });
            }

            @Override
            public void onClientMessage(int clientId, String threadName, String receivedText, String sentText) {
                SwingUtilities.invokeLater(() -> {
                    appendLog(String.format("[%s] [Client-%d] Received: \"%s\" -> Sending: \"%s\"",
                            threadName, clientId, receivedText, sentText));
                });
            }

            @Override
            public void onClientDisconnected(int clientId, String status) {
                SwingUtilities.invokeLater(() -> {
                    DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
                    for (int i = 0; i < model.getRowCount(); i++) {
                        Object idObj = model.getValueAt(i, 0);
                        if (idObj instanceof Integer && ((Integer) idObj) == clientId) {
                            model.setValueAt("Hoàn tất (" + status + ")", i, 3);
                            break;
                        }
                    }
                    appendLog(String.format("-> [Ngắt kết nối] Client #%d đã kết thúc phiên làm việc.", clientId));
                });
            }

            @Override
            public void onServerStopped() {
                SwingUtilities.invokeLater(() -> {
                    btnStart.setEnabled(true);
                    txtPort.setEnabled(true);
                    txtPoolSize.setEnabled(true);
                    btnStop.setEnabled(false);

                    progressBar.setIndeterminate(false);
                    progressBar.setValue(0);
                    progressBar.setString("Đã dừng");
                    lblStatus.setText("Trạng thái: Máy chủ đã dừng");
                    appendLog("-> [Server] Đã dừng và giải phóng toàn bộ tài nguyên.\n");
                });
            }
        });

        // Chay Server loop tren background SwingWorker
        serverWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                server.start();
                return null;
            }
        };
        serverWorker.execute();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * Xu ly su kien nut Stop Server.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        stopServer();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * Dung Server an toan.
     */
    private void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (serverWorker != null && !serverWorker.isDone()) {
            serverWorker.cancel(true);
        }
    }

    /**
     * Chen chuoi vao JTextArea txtLog va tu dong cuon.
     */
    private void appendLog(String log) {
        txtLog.append(log + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblClients;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblPoolSize;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlClients;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpClients;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JTable tblClients;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPoolSize;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
