package nhanh4;

import java.awt.Font;
import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien TCP Client (Socket TCP) - Mo hinh Client / Server co ban.
 *
 * Chuc nang chinh:
 * 1. Nhap thong tin Server Host (mac dinh: localhost) va Port (mac dinh: 9090).
 * 2. Gui chuoi ky tu bat ky den Server qua Socket TCP va nhan phan hoi: "Server: Received OK".
 * 3. Tinh toan thoi gian phan hoi (round-trip latency) tinh bang mili-giay (ms).
 * 4. Kiem thu tu dong (Automated Test) voi chuoi "Xin chao" theo dung dac ta bao cao.
 * 5. Luu tru toan bo lich su truyen tin vao JTable.
 */
public class ClientForm extends javax.swing.JFrame {

    private int sendCounter = 0;
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblHistory.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblHistory.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblHistory.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(2).setPreferredWidth(180);
        tblHistory.getColumnModel().getColumn(3).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(4).setPreferredWidth(90);
        tblHistory.getColumnModel().getColumn(5).setPreferredWidth(110);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblHistory.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tblHistory.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

        txtLog.append("=== TCP CLIENT (SOCKET TCP) SẴN SÀNG ===\n");
        txtLog.append("- Nhập địa chỉ Server Host, Port và chuỗi tin nhắn cần gửi.\n");
        txtLog.append("- Bấm 'Gửi (Send)' hoặc nhấn phím Enter để truyền chuỗi qua Socket.\n");
        txtLog.append("- Nhận phản hồi từ Server theo định dạng: Server: Received OK.\n");
        txtLog.append("- Bấm 'Kiểm Thử Tự Động' để chạy test case mẫu với chuỗi 'Xin chao'.\n\n");
    }

    private void appendLog(String message) {
        txtLog.append(message + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfig = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnAutoTest = new javax.swing.JButton();
        pnlMessage = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlHistory = new javax.swing.JPanel();
        lblHistory = new javax.swing.JLabel();
        scpHistory = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 4 - TCP Client (Socket TCP)");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TCP CLIENT - TRUYỀN NHẬN THÔNG ĐIỆP QUA SOCKET TCP");
        pnlConfig.add(lblTitle);

        lblHost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHost.setText("Server Host:");
        pnlConfig.add(lblHost);

        txtHost.setText("localhost");
        txtHost.setToolTipText("Địa chỉ IP hoặc hostname máy chủ");
        pnlConfig.add(txtHost);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlConfig.add(lblPort);

        txtPort.setText("9090");
        txtPort.setToolTipText("Cổng Server (mặc định 9090)");
        pnlConfig.add(txtPort);

        btnAutoTest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAutoTest.setText("Kiểm Thử Tự Động");
        btnAutoTest.setToolTipText("Tự động gửi chuỗi 'Xin chao' và kiểm tra phản hồi 'Received OK'");
        btnAutoTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoTestActionPerformed(evt);
            }
        });
        pnlConfig.add(btnAutoTest);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMessage.setText("Chuỗi gửi:");
        pnlMessage.add(lblMessage);

        txtMessage.setText("Xin chao");
        txtMessage.setToolTipText("Nhập chuỗi và nhấn Enter hoặc bấm Gửi (Send)");
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        pnlMessage.add(txtMessage);

        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setText("Gửi (Send)");
        btnSend.setToolTipText("Gửi chuỗi qua Socket TCP và nhận phản hồi");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        pnlMessage.add(btnSend);

        btnClearLog.setText("Xóa Lịch Sử");
        btnClearLog.setToolTipText("Xóa nhật ký log và bảng lịch sử");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        pnlMessage.add(btnClearLog);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Sẵn sàng");
        pnlMessage.add(lblStatus);

        progressBar.setString("Sẵn sàng gửi");
        progressBar.setStringPainted(true);
        pnlMessage.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ TRUYỀN NHẬN (CLIENT LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHistory.setText("LỊCH SỬ GỬI VÀ PHẢN HỒI TỬ SERVER:");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Thời gian", "Chuỗi gửi", "Phản hồi Server", "Độ trễ (ms)", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistory.setRowHeight(22);
        scpHistory.setViewportView(tblHistory);

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpHistory)
                    .addGroup(pnlHistoryLayout.createSequentialGroup()
                        .addComponent(lblHistory)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien khi nhan Enter trong txtMessage.
     */
    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        executeSendMessage();
    }//GEN-LAST:event_txtMessageActionPerformed

    /**
     * Xu ly su kien nut Send.
     */
    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        executeSendMessage();
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * Xu ly su kien nut Kiem Thu Tu Dong.
     */
    private void btnAutoTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoTestActionPerformed
        txtMessage.setText("Xin chao");
        executeSendMessage();
    }//GEN-LAST:event_btnAutoTestActionPerformed

    /**
     * Xu ly su kien nut Xoa Lich Su.
     */
    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtLog.setText("");
        DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
        model.setRowCount(0);
        sendCounter = 0;
        appendLog("-> Đã xóa sạch lịch sử truyền tin và nhật ký log.\n");
    }//GEN-LAST:event_btnClearLogActionPerformed

    /**
     * Thuc thi gui thong diep qua Socket TCP tren SwingWorker.
     */
    private void executeSendMessage() {
        String host = txtHost.getText().trim();
        if (host.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ Server Host!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int port;
        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port phải nằm trong khoảng (1 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String message = txtMessage.getText();
        if (message == null || message.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chuỗi cần gửi!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        btnSend.setEnabled(false);
        btnAutoTest.setEnabled(false);
        txtMessage.setEnabled(false);
        progressBar.setIndeterminate(true);
        progressBar.setString("Đang gửi qua Socket TCP...");
        lblStatus.setText(String.format("Trạng thái: Đang kết nối tới %s:%d...", host, port));

        SwingWorker<String, String> worker = new SwingWorker<String, String>() {
            private long elapsedMs = 0;
            private boolean success = false;
            private String timeStr = "";

            @Override
            protected String doInBackground() throws Exception {
                timeStr = LocalTime.now().format(timeFormatter);
                publish(String.format("-> [Client] Kết nối tới TCP Server %s:%d...", host, port));
                publish(String.format("-> [Client] Gửi chuỗi: \"%s\"", message));

                long start = System.currentTimeMillis();
                TCPClient client = new TCPClient(host, port);
                String reply = client.sendMessage(message);
                elapsedMs = System.currentTimeMillis() - start;

                success = true;
                return reply;
            }

            @Override
            protected void process(List<String> chunks) {
                for (String chunk : chunks) {
                    appendLog(chunk);
                }
            }

            @Override
            protected void done() {
                try {
                    String reply = get();
                    // In theo dung dac ta yeu cau: Server: Received OK
                    appendLog("Server: " + reply);
                    appendLog(String.format("-> [Hoàn tất] Nhận phản hồi sau %d ms\n", elapsedMs));

                    sendCounter++;
                    boolean isExpected = "Received OK".equalsIgnoreCase(reply != null ? reply.trim() : "");
                    String statusText = isExpected ? "Thành công (OK)" : "Phản hồi khác";

                    DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
                    model.addRow(new Object[]{sendCounter, timeStr, message, reply, elapsedMs, statusText});

                    lblStatus.setText(String.format("Trạng thái: Hoàn tất (%d ms) - Server: %s", elapsedMs, reply));
                    progressBar.setString("Gửi thành công");

                } catch (Exception e) {
                    String errorMsg = e.getCause() != null ? e.getCause().getMessage() : e.getMessage();
                    appendLog("[Lỗi kết nối] " + errorMsg);
                    appendLog("-> Gợi ý: Hãy đảm bảo TCPServer đã được bật và đang lắng nghe đúng cổng " + port + ".\n");

                    sendCounter++;
                    String timeNow = LocalTime.now().format(timeFormatter);
                    DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
                    model.addRow(new Object[]{sendCounter, timeNow, message, "[Lỗi] " + errorMsg, elapsedMs, "Thất bại"});

                    lblStatus.setText("Trạng thái: Lỗi kết nối!");
                    progressBar.setString("Thất bại");
                } finally {
                    progressBar.setIndeterminate(false);
                    btnSend.setEnabled(true);
                    btnAutoTest.setEnabled(true);
                    txtMessage.setEnabled(true);
                    txtMessage.requestFocusInWindow();
                    txtMessage.selectAll();
                }
            }
        };

        worker.execute();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Look and Feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()) || "Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoTest;
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpHistory;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
