package nhanh4;

import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Giao dien TCP Server co ban (Socket TCP) - Mo hinh Client / Server.
 *
 * Chuc nang chinh:
 * 1. Cau hinh cong Port TCP lang nghe (mac dinh: 9090).
 * 2. Start / Stop Server an toan tren SwingWorker, tranh lam do UI (EDT).
 * 3. Hien thi log chi tiet: Bat tay 3 buoc TCP, Client ket noi, chuoi nhan, phan hoi 'Received OK'.
 * 4. Luu tru danh sach cac ban tin trao doi vao JTable realtime.
 */
public class ServerForm extends javax.swing.JFrame {

    private TCPServer server;
    private SwingWorker<Void, Void> serverWorker;
    private int messageCounter = 0;
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        customInit();
    }

    /**
     * Thiet lap tuy bien giao dien ban dau.
     */
    private void customInit() {
        setLocationRelativeTo(null);

        // Dinh dang JTable
        tblMessages.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblMessages.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblMessages.getColumnModel().getColumn(1).setPreferredWidth(170);
        tblMessages.getColumnModel().getColumn(2).setPreferredWidth(90);
        tblMessages.getColumnModel().getColumn(3).setPreferredWidth(220);
        tblMessages.getColumnModel().getColumn(4).setPreferredWidth(150);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblMessages.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblMessages.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

        // Xu ly su kien khi dong Form thi tu dong dung Server an toan
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                stopServer();
            }
        });

        txtLog.append("=== MÁY CHỦ TCP CƠ BẢN (SOCKET TCP) SẴN SÀNG ===\n");
        txtLog.append("- Cấu hình cổng Port TCP (mặc định: 9090).\n");
        txtLog.append("- Bấm 'Start Server' để bắt đầu lắng nghe kết nối từ Client.\n");
        txtLog.append("- Khi Client gửi chuỗi, Server hiển thị: Client says: \"<nội dung>\" và phản hồi: \"Received OK\".\n");
        txtLog.append("- Bấm 'Stop Server' để đóng cổng ServerSocket an toàn.\n\n");
    }

    private void appendLog(String message) {
        txtLog.append(message + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlLog = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        scpLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlMessages = new javax.swing.JPanel();
        lblMessages = new javax.swing.JLabel();
        scpMessages = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhánh 4 - TCP Server Cơ Bản (Socket TCP)");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MÁY CHỦ TCP CƠ BẢN - KIẾN TRÚC CLIENT / SERVER (SOCKET TCP)");
        pnlControl.add(lblTitle);

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPort.setText("Port:");
        pnlControl.add(lblPort);

        txtPort.setText("9090");
        txtPort.setToolTipText("Cổng TCP lắng nghe (mặc định 9090)");
        pnlControl.add(txtPort);

        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart.setText("Start Server");
        btnStart.setToolTipText("Khởi động Server trên SwingWorker");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pnlControl.add(btnStart);

        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStop.setText("Stop Server");
        btnStop.setToolTipText("Dừng Server và đóng cổng ServerSocket");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        pnlControl.add(btnStop);

        btnClearLog.setText("Xóa Nhật Ký");
        btnClearLog.setToolTipText("Xóa toàn bộ dòng log và bảng tin nhắn");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        pnlControl.add(btnClearLog);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Trạng thái: Chưa khởi động");
        pnlControl.add(lblStatus);

        progressBar.setString("Sẵn sàng");
        progressBar.setStringPainted(true);
        pnlControl.add(progressBar);

        lblLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLog.setText("NHẬT KÝ MÁY CHỦ (SERVER LOG):");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        scpLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpLog)
                    .addGroup(pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLog, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMessages.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMessages.setText("LỊCH SỬ THÔNG ĐIỆP NHẬN VÀ PHẢN HỒI:");

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Client IP", "Thời gian", "Nội dung nhận (Client says)", "Phản hồi gửi (Server reply)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMessages.setRowHeight(22);
        scpMessages.setViewportView(tblMessages);

        javax.swing.GroupLayout pnlMessagesLayout = new javax.swing.GroupLayout(pnlMessages);
        pnlMessages.setLayout(pnlMessagesLayout);
        pnlMessagesLayout.setHorizontalGroup(
            pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpMessages)
                    .addGroup(pnlMessagesLayout.createSequentialGroup()
                        .addComponent(lblMessages)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMessagesLayout.setVerticalGroup(
            pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMessages, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMessages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Xu ly su kien nut Start Server.
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        int port;

        try {
            port = Integer.parseInt(txtPort.getText().trim());
            if (port <= 1024 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Port hợp lệ (1025 - 65535)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port phải là một số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        btnStart.setEnabled(false);
        txtPort.setEnabled(false);
        btnStop.setEnabled(true);

        progressBar.setIndeterminate(true);
        progressBar.setString(String.format("Server RUNNING tai port %d", port));
        lblStatus.setText(String.format("Trạng thái: Đang lắng nghe kết nối trên cổng %d...", port));

        // Khoi tao Server va gan Listener cap nhat giao dien
        server = new TCPServer(port);
        server.setListener(new TCPServerListener() {
            @Override
            public void onLog(String message) {
                SwingUtilities.invokeLater(() -> appendLog(message));
            }

            @Override
            public void onServerStarted(int p) {
                SwingUtilities.invokeLater(() -> {
                    lblStatus.setText(String.format("Trạng thái: Đang lắng nghe trên cổng TCP %d...", p));
                    progressBar.setString(String.format("Listening on port %d...", p));
                    appendLog(String.format("-> [TCPServer] Khởi động thành công, đang lắng nghe tại cổng TCP: %d", p));
                });
            }

            @Override
            public void onClientConnected(String clientAddress) {
                SwingUtilities.invokeLater(() -> {
                    lblStatus.setText(String.format("Trạng thái: Đang phục vụ Client từ %s", clientAddress));
                    progressBar.setString(String.format("Serving Client: %s", clientAddress));
                    appendLog(String.format("[Server] Đã chấp nhận kết nối TCP từ Client: %s", clientAddress));
                });
            }

            @Override
            public void onMessageReceived(String clientAddress, String receivedText, String sentReply) {
                SwingUtilities.invokeLater(() -> {
                    String timeStr = LocalTime.now().format(timeFormatter);
                    messageCounter++;

                    // Cap nhat log theo dung dac ta
                    appendLog(String.format("Client says: \"%s\"", receivedText));
                    appendLog(String.format("[Server] Đã gửi phản hồi: \"%s\"", sentReply));

                    // Cap nhat vao JTable
                    DefaultTableModel model = (DefaultTableModel) tblMessages.getModel();
                    model.addRow(new Object[]{messageCounter, clientAddress, timeStr, receivedText, sentReply});
                });
            }

            @Override
            public void onClientDisconnected(String clientAddress) {
                SwingUtilities.invokeLater(() -> {
                    appendLog(String.format("[Server] Client %s đã đóng kết nối. Chờ Client tiếp theo...\n", clientAddress));
                    lblStatus.setText(String.format("Trạng thái: Đang lắng nghe trên cổng TCP %d...", port));
                    progressBar.setString(String.format("Listening on port %d...", port));
                });
            }

            @Override
            public void onServerStopped() {
                SwingUtilities.invokeLater(() -> {
                    lblStatus.setText("Trạng thái: Đã dừng");
                    progressBar.setIndeterminate(false);
                    progressBar.setString("Đã dừng (Stopped)");
                    btnStart.setEnabled(true);
                    txtPort.setEnabled(true);
                    btnStop.setEnabled(false);
                    appendLog("-> [TCPServer] Server đã dừng và đóng cổng ServerSocket an toàn.\n");
                });
            }
        });

        // Chay Server loop trong SwingWorker de khong gay block giao dien
        serverWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                server.start();
                return null;
            }

            @Override
            protected void done() {
                // Dam bao UI tro lai trang thai binh thuong neu worker ket thuc
                lblStatus.setText("Trạng thái: Đã dừng");
                progressBar.setIndeterminate(false);
                progressBar.setString("Đã dừng");
                btnStart.setEnabled(true);
                txtPort.setEnabled(true);
                btnStop.setEnabled(false);
            }
        };

        serverWorker.execute();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * Xu ly su kien nut Stop Server.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        stopServer();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * Xu ly su kien nut Xoa Nhat Ky.
     */
    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtLog.setText("");
        DefaultTableModel model = (DefaultTableModel) tblMessages.getModel();
        model.setRowCount(0);
        messageCounter = 0;
        appendLog("-> Đã xóa sạch nhật ký và bảng thông điệp.\n");
    }//GEN-LAST:event_btnClearLogActionPerformed

    /**
     * Phuong thuc dung Server an toan.
     */
    private void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (serverWorker != null && !serverWorker.isDone()) {
            serverWorker.cancel(true);
        }
        btnStart.setEnabled(true);
        txtPort.setEnabled(true);
        btnStop.setEnabled(false);
        progressBar.setIndeterminate(false);
        progressBar.setString("Đã dừng");
        lblStatus.setText("Trạng thái: Đã dừng");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Look and Feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()) || "Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMessages;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlMessages;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scpLog;
    private javax.swing.JScrollPane scpMessages;
    private javax.swing.JTable tblMessages;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
